# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea716b80178769a4e36cde4d081b73dd65018a2ea100aced162c6d40e7d651640a19b4bc1ece90f2bb9babc433b301b675cff07ece31f043d07e0dab43685274

test:
  secret_key_base: 81c05ada387705f606c82dc4f5f2c38c8677d030a72818b6e281614ca1524da784313e167ac675da746ebe3e897986fb00a5517cd95adc3db62ebc70299a0544

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
